title: Practice Blog
author: GitHub User
email: your-email@domain.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  This is a practice blog to get oriented with Github pages and celebrate a cheesy pun.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
